displayName: Encrypt Body
summary: Encrypt the HTTP response body by replacing a search regex by a replacement string.
type: middleware
import: github.com/traefik/plugin-encrypt-body
compatibility: TODO
testData:
  lastModified: true
  rewrites:
    - regex: "bar"
      replacement: "foo"
